# Bazarr Reverse Proxy Configuration

<Location /bazarr/>
    ProxyPass http://bazarr:6767/bazarr/
    ProxyPassReverse http://bazarr:6767/bazarr/
    ProxyPreserveHost On
    RequestHeader set X-Real-IP %{REMOTE_ADDR}s
    RequestHeader set X-Forwarded-For "%{REMOTE_ADDR}s"
    RequestHeader set X-Forwarded-Proto "https"
    RequestHeader set X-Forwarded-Host "%{HTTP_HOST}s"
</Location>
