# Bazarr Reverse Proxy Configuration

ProxyPass /bazarr/ http://bazarr:6767/bazarr/
ProxyPassReverse /bazarr/ http://bazarr:6767/bazarr/

<Location /bazarr/>
    ProxyPreserveHost On
    RequestHeader set X-Real-IP %{REMOTE_ADDR}s
    RequestHeader set X-Forwarded-For "%{REMOTE_ADDR}s"
    RequestHeader set X-Forwarded-Proto "%{REQUEST_SCHEME}e"
    RequestHeader set X-Forwarded-Host "%{HTTP_HOST}s"
</Location>


