ProxyPass /deluge http://deluge:8112/
ProxyPassReverse /deluge http://deluge:8112/
ProxyPassReverseCookieDomain deluge localhost
ProxyPassReverseCookiePath / /deluge/

<Location /deluge>
    AuthType openid-connect
    Require valid-user
    RequestHeader set X-Deluge-Base "/deluge/"

    # Headers for websocket support
    ProxyPreserveHost On
    RequestHeader set X-Real-IP %{REMOTE_ADDR}s
    RequestHeader set X-Forwarded-For %{HTTP:X-Forwarded-For}e
    RequestHeader set X-Forwarded-Proto "%{REQUEST_SCHEME}e"
    RequestHeader set X-Forwarded-Host %{HTTP_HOST}e
</Location>

