# Jackett Reverse Proxy Configuration
ProxyPass /jackett http://jackett:9117/jackett nocanon
ProxyPassReverse /jackett http://jackett:9117/jackett
ProxyPass /jackett/api http://jackett:9117/jackett/api nocanon
ProxyPassReverse /jackett/api http://jackett:9117/jackett/api

<Location /jackett>

    # Jackett-specific settings
    ProxyPreserveHost On
    RequestHeader set X-Real-IP %{REMOTE_ADDR}s
    RequestHeader set X-Forwarded-For %{HTTP:X-Forwarded-For}e
    RequestHeader set X-Forwarded-Proto "https"
    RequestHeader set X-Forwarded-Host %{HTTP_HOST}e
</Location>

