# Jellyfin Reverse Proxy Configuration
# Based on official Jellyfin documentation

ProxyPass /jellyfin/socket "ws://@@JELLYFIN_URL_WS@@/jellyfin/socket"
ProxyPassReverse /jellyfin/socket "ws://@@JELLYFIN_URL_WS@@/jellyfin/socket"
ProxyPass /jellyfin "@@JELLYFIN_URL@@/jellyfin"
ProxyPassReverse /jellyfin "@@JELLYFIN_URL@@/jellyfin"

<Location /jellyfin/socket>
    AuthType openid-connect
    Require valid-user
    ProxyPreserveHost On
</Location>

<Location /jellyfin>
    AuthType openid-connect
    Require valid-user
    ProxyPreserveHost On
    RequestHeader set X-Real-IP %{REMOTE_ADDR}s
    RequestHeader set X-Forwarded-For "%{REMOTE_ADDR}s"
    RequestHeader set X-Forwarded-Proto "%{REQUEST_SCHEME}e"
    RequestHeader set X-Forwarded-Host "%{HTTP_HOST}s"
</Location>

