# Jellyfin Reverse Proxy Configuration
# Based on official Jellyfin documentation

<LocationMatch ^/jellyfin(/.*)?$>
    ProxyPreserveHost On
    ProxyPass @@JELLYFIN_URL@@/jellyfin
    ProxyPassReverse @@JELLYFIN_URL@@/jellyfin
    RequestHeader set X-Real-IP %{REMOTE_ADDR}s
    RequestHeader set X-Forwarded-For "%{REMOTE_ADDR}s"
    RequestHeader set X-Forwarded-Proto "https"
    RequestHeader set X-Forwarded-Host "%{HTTP_HOST}s"
</LocationMatch>

<LocationMatch ^/jellyfin/socket(/.*)?$>
    ProxyPreserveHost On
    ProxyPass ws://@@JELLYFIN_URL_WS@@/jellyfin/socket
    ProxyPassReverse ws://@@JELLYFIN_URL_WS@@/jellyfin/socket
</LocationMatch>
