# Maintainerr Reverse Proxy Configuration

<Location /maintainerr/>
    ProxyPass http://maintainerr:6246/maintainerr/
    ProxyPassReverse http://maintainerr:6246/maintainerr/
    ProxyPreserveHost On
    RequestHeader set X-Real-IP %{REMOTE_ADDR}s
    RequestHeader set X-Forwarded-For "%{REMOTE_ADDR}s"
    RequestHeader set X-Forwarded-Proto "https"
    RequestHeader set X-Forwarded-Host "%{HTTP_HOST}s"
</Location>
