# Plex Reverse Proxy Configuration
ProxyPass /plex http://plex:32400/plex
ProxyPassReverse /plex http://plex:32400/plex
ProxyPass /plex/web http://plex:32400/plex/web
ProxyPassReverse /plex/web http://plex:32400/plex/web

<Location /plex>
    AuthType openid-connect
    Require valid-user
    ProxyPreserveHost On
    RequestHeader set X-Real-IP %{REMOTE_ADDR}s
    RequestHeader set X-Forwarded-For %{HTTP:X-Forwarded-For}e
    RequestHeader set X-Forwarded-Proto "%{REQUEST_SCHEME}e"
    RequestHeader set X-Forwarded-Host %{HTTP_HOST}e
    RequestHeader set X-Remote-User %{REMOTE_USER}s
</Location>

<Location /plex/web>
    AuthType openid-connect
    Require valid-user
</Location>

