# Radarr Reverse Proxy Configuration
ProxyPass /radarr http://radarr:7878/radarr
ProxyPassReverse /radarr http://radarr:7878/radarr
ProxyPass /radarr/api http://radarr:7878/radarr/api
ProxyPassReverse /radarr/api http://radarr:7878/radarr/api
ProxyPass /radarr/login http://radarr:7878/radarr/login
ProxyPassReverse /radarr/login http://radarr:7878/radarr/login
ProxyPass /radarr/signalr ws://radarr:7878/radarr/signalr
ProxyPassReverse /radarr/signalr ws://radarr:7878/radarr/signalr

<Location /radarr>
    AuthType openid-connect
    Require valid-user
    ProxyPreserveHost On
    RequestHeader set X-Real-IP %{REMOTE_ADDR}s
    RequestHeader set X-Forwarded-For %{HTTP:X-Forwarded-For}e
    RequestHeader set X-Forwarded-Proto "%{REQUEST_SCHEME}e"
    RequestHeader set X-Forwarded-Host %{HTTP_HOST}e
</Location>

<Location /radarr/api>
    AuthType openid-connect
    Require valid-user
</Location>

<Location /radarr/login>
    AuthType openid-connect
    Require valid-user
</Location>

<Location /radarr/signalr>
    AuthType openid-connect
    Require valid-user
</Location>

