# Tautulli Reverse Proxy Configuration
ProxyPass /tautulli http://tautulli:8181/tautulli/
ProxyPassReverse /tautulli http://tautulli:8181/tautulli/

<Location /tautulli>
    AuthType openid-connect
    Require valid-user
    RequestHeader set Host %{HTTP_HOST}s
    RequestHeader set X-Forwarded-Host %{SERVER_NAME}s
    RequestHeader set X-Real-IP %{REMOTE_ADDR}s
    RequestHeader set X-Forwarded-For %{PROXY_ADD_X_FORWARDED_FOR}s
    RequestHeader set X-Forwarded-Proto %{REQUEST_SCHEME}s
    SetEnvIf X-Forwarded-Proto "https" X-Forwarded-Ssl=on
</Location>

