# Tautulli Reverse Proxy Configuration
<Location /tautulli/>
    ProxyPreserveHost On
    ProxyPass http://tautulli:8181/
    ProxyPassReverse http://tautulli:8181/

    # Headers for proper operation and iframe embedding
    RequestHeader set X-Real-IP %{REMOTE_ADDR}s
    RequestHeader set X-Forwarded-For %{HTTP:X-Forwarded-For}e
    RequestHeader set X-Forwarded-Proto "https"
    RequestHeader set X-Forwarded-Host %{HTTP_HOST}e
    RequestHeader set X-Script-Name "/tautulli"
    RequestHeader set X-Forwarded-Prefix "/tautulli"
</Location>
